# Generated by Django 2.0.4 on 2018-07-11 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookie', '0002_auto_20180711_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookieprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
