# Generated by Django 2.0.4 on 2018-07-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookie', '0004_bookieinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookieprofile',
            name='email',
            field=models.EmailField(default='anywhere@anyhow.com', max_length=254),
        ),
    ]
