version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000 --settings=chillbet.localhost
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db