version: '2'
services:
  web:
    image: 923516984695.dkr.ecr.us-east-1.amazonaws.com/chillbet:latest
    command: python3 manage.py runserver 0.0.0.0:8000 --settings=chillbet.production
    ports:
      - "8000:8000"
    logging:
      driver: awslogs
      options: 
        awslogs-group: chill-bet
        awslogs-region: us-east-1
        awslogs-stream-prefix: web      