# Generated by Django 2.0.2 on 2018-02-22 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('better', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='team',
        ),
        migrations.AddField(
            model_name='contest',
            name='line',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contest',
            name='overUnder',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contest',
            name='awayTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awayTeam', to='better.Team'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='contest_date',
            field=models.DateTimeField(verbose_name='Date Of Contest'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='homeTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeTeam', to='better.Team'),
        ),
        migrations.DeleteModel(
            name='Contestant',
        ),
    ]
