# Generated by Django 2.0.4 on 2018-04-04 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('better', '0003_auto_20180222_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableBets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamName', models.CharField(max_length=200)),
                ('sport', models.CharField(choices=[('O/U', 'Over Under'), ('line', 'Bet on the line'), ('moneyline', 'moneyline bet')], default='straight', max_length=100)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet', to='better.Contest')),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Date Of Contest')),
                ('userMakingBet', models.CharField(max_length=200)),
                ('line', models.FloatField()),
                ('amountOfBet', models.FloatField()),
                ('approved', models.BooleanField()),
                ('outcome', models.CharField(max_length=1)),
                ('numberOfBet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='betnumber', to='better.AvailableBets')),
            ],
        ),
    ]
