# Generated by Django 2.0.4 on 2018-04-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better', '0004_availablebets_bet'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='teamAbbreviation',
            field=models.CharField(default='XXX', max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='sport',
            field=models.CharField(choices=[('NCAAF', 'NCAA Football'), ('NCAABB', 'NCAA Baseball'), ('NCAAM', 'NCAA Mens Basketball'), ('NCAAW', 'NCAA Womens Basketball'), ('MLB', 'Major League Baseball')], default='NCAAF', max_length=100),
        ),
    ]
