# Generated by Django 2.0.2 on 2018-04-22 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('better', '0005_auto_20180420_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='teamPhoto',
            new_name='teamLogo',
        ),
        migrations.RemoveField(
            model_name='availablebets',
            name='teamName',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='contestPhoto',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='line',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='overUnder',
        ),
        migrations.AddField(
            model_name='availablebets',
            name='odds',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='availablebets',
            name='overunder',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='availablebets',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availableBet', to='better.Contest'),
        ),
        migrations.AlterField(
            model_name='availablebets',
            name='sport',
            field=models.CharField(choices=[('O/U', 'Over Under (totals)'), ('line', 'Bet on the line'), ('moneyline', 'moneyline bet'), ('runline', 'runline bet')], default='straight', max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='sport',
            field=models.CharField(choices=[('NCAAF', 'NCAA Football'), ('NCAABB', 'NCAA Baseball'), ('NCAAM', 'NCAA Mens Basketball'), ('NCAAW', 'NCAA Womens Basketball'), ('MLB', 'Major League Baseball')], default='MLB', max_length=100),
        ),
    ]
