# Generated by Django 2.0.2 on 2018-04-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better', '0006_auto_20180422_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teamLogo',
            field=models.CharField(default='XXX', max_length=200),
        ),
    ]
