# Generated by Django 2.0.4 on 2018-04-26 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('better', '0007_auto_20180422_0444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availablebets',
            old_name='overunder',
            new_name='spread',
        ),
        migrations.RemoveField(
            model_name='availablebets',
            name='sport',
        ),
        migrations.AddField(
            model_name='availablebets',
            name='bettype',
            field=models.CharField(choices=[('spread', 'Bet on the line'), ('moneyline', 'moneyline bet'), ('total', 'runline bet')], default='spread', max_length=100),
        ),
        migrations.AddField(
            model_name='availablebets',
            name='overorunder',
            field=models.CharField(choices=[('under', 'total score will score over this many points'), ('over', 'total score will be under this many points'), ('na', 'na')], default='na', max_length=10),
        ),
        migrations.AddField(
            model_name='availablebets',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team', to='better.Team'),
        ),
    ]
