# Generated by Django 2.0.4 on 2018-06-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better', '0008_auto_20180426_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='awayScore',
            field=models.IntegerField(default=0, verbose_name='Away Score'),
        ),
        migrations.AddField(
            model_name='contest',
            name='gamePhase',
            field=models.CharField(choices=[('upcoming', 'This game is in the future'), ('ongoing', 'This game is currently being played'), ('final', 'this game is over')], default='upcoming', max_length=100),
        ),
        migrations.AddField(
            model_name='contest',
            name='homeScore',
            field=models.IntegerField(default=0, verbose_name='Home Score'),
        ),
    ]
