# Generated by Django 2.0.4 on 2018-07-11 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookie', '0002_auto_20180711_2203'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('better', '0009_auto_20180619_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetterProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('bookie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bookie', to='bookie.BookieProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
