# Generated by Django 2.0.4 on 2018-07-11 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('better', '0010_betterprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betterprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
